import { IMAGES } from "./images";

const reactjsProjects = [
  {
    image: IMAGES.lotterySite,
    title: "Lottery Site",
    desc: "A lottery website with responsive layout. Only implement Home and Play routes.",
    stack: ["React", "React Router", "Redux toolkit", "Sass"],
    code: "https://github.com/SonDo580/lottery-clone",
    live: "https://sondo-lottery-clone.netlify.app",
  },
  {
    image: IMAGES.memoryCards,
    title: "Memory Cards",
    desc: "A fun memory game. Try to select each card only once.",
    stack: ["React"],
    code: "https://github.com/SonDo580/memory-card",
    live: "https://SonDo580.github.io/memory-card",
  },
  {
    image: IMAGES.shoppingCart,
    title: "Shopping Cart",
    desc: "A simple E-Commerce site with basic functionality.",
    stack: ["React", "React Router", "Redux toolkit", "MirageJS", "Sass"],
    code: "https://github.com/SonDo580/shopping-cart",
    live: "https://SonDo580.github.io/shopping-cart",
  },
  {
    image: IMAGES.cvApp,
    title: "CV Application",
    desc: "A simple CV creator.",
    stack: ["React"],
    code: "https://github.com/SonDo580/CV-application",
    live: "https://SonDo580.github.io/CV-application",
  },
  {
    image: IMAGES.crownClothing,
    title: "Crown Clothing",
    desc: "An online clothing store (guided project). I implemented most of the things myself.",
    stack: [
      "React",
      "React Router",
      "Redux",
      "Redux Saga",
      "Firebase",
      "styled-components",
    ],
    code: "https://github.com/SonDo580/crown-clothing",
    live: "https://sondo-crown-clothing.netlify.app",
  },
  {
    image: IMAGES.githubBattle,
    title: "GitHub Battle",
    desc: "Show popular repos on GitHub and compare scores between 2 GitHub users (guided project).",
    stack: ["React", "React Router"],
    code: "https://github.com/SonDo580/github-battle",
    live: "https://github-battle-vert.vercel.app",
  },
  {
    image: IMAGES.photoApp,
    title: "Photo App",
    desc: "A simple app to manage photos (guided project).",
    stack: [
      "React",
      "React Router",
      "Redux toolkit",
      "Formik",
      "Reactstrap",
      "Axios",
    ],
    code: "https://github.com/SonDo580/photo-app",
    live: "https://sondo-photo-app.surge.sh",
  },
  {
    image: IMAGES.todoRedux,
    title: "Todo App",
    desc: "A simple app to manage todo list (guided project).",
    stack: ["React", "Redux", "Ant Design", "MirageJS"],
    code: "https://github.com/SonDo580/todo-redux",
    live: "http://sondo-todo-redux.surge.sh",
  },
];

const javascriptProjects = [
  {
    image: IMAGES.todoList,
    title: "Todo List",
    desc: "A simple todo app. Built to practice DOM manipulation, modules, webpack.",
    stack: ["JavaScript", "CSS"],
    code: "https://github.com/SonDo580/todo-list",
    live: "https://sondo580.github.io/todo-list",
  },
  {
    image: IMAGES.restaurantPage,
    title: "Restaurant Page",
    desc: "A website to show restaurant information. Built to practice DOM manipulation, modules, webpack.",
    stack: ["JavaScript", "CSS"],
    code: "https://github.com/SonDo580/restaurant-page",
    live: "https://sondo580.github.io/restaurant-page",
  },
  {
    image: IMAGES.weatherApp,
    title: "Weather App",
    desc: "Search weather by location. Built to practice working with API.",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/weather-app",
    live: "https://sondo580.github.io/weather-app",
  },
  {
    image: IMAGES.ticTacToe,
    title: "Tic Tac Toe",
    desc: "Tic Tac Toe game. Built to practice factory functions and the module pattern (with IIFE).",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/tic-tac-toe",
    live: "https://sondo580.github.io/tic-tac-toe",
  },
  {
    image: IMAGES.library,
    title: "Library App",
    desc: "Simple library app. Built to practice using object constructor.",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/library",
    live: "https://sondo580.github.io/library",
  },
  {
    image: IMAGES.calculator,
    title: "Calculator",
    desc: "A simple calculator. Built to practice JavaScript",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/simple-calculator",
    live: "https://sondo580.github.io/simple-calculator",
  },
  {
    image: IMAGES.rockPaperScissors,
    title: "Rock Paper Scissors",
    desc: "A traditional game. Built to practice JavaScript",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/rock-paper-scissors",
    live: "https://sondo580.github.io/rock-paper-scissors",
  },
  {
    image: IMAGES.sketchingPad,
    title: "Sketching Pad",
    desc: "Hover a square to highlight it. Use random color each time.",
    stack: ["HTML", "CSS", "JavaScript"],
    code: "https://github.com/SonDo580/etch-a-sketch",
    live: "https://sondo580.github.io/etch-a-sketch",
  },
];

const htmlProjects = [
  {
    image: IMAGES.adminDashboard,
    title: "Admin Dashboard",
    desc: "Admin Dashboard with both flex and grid layout",
    stack: ["HTML", "CSS"],
    code: "https://github.com/SonDo580/admin-dashboard",
    live: "https://sondo580.github.io/admin-dashboard",
  },
  {
    image: IMAGES.landingPage,
    title: "Landing Page",
    desc: "A static landing page built from given design",
    stack: ["HTML", "CSS"],
    code: "https://github.com/SonDo580/odin-landing-page",
    live: "https://sondo580.github.io/odin-landing-page",
  },
  {
    image: IMAGES.signupForm,
    title: "Signup Form",
    desc: "A basic sign-up form.",
    stack: ["HTML", "CSS"],
    code: "https://github.com/SonDo580/sign-up-form",
    live: "https://sondo580.github.io/sign-up-form",
  },
];

const nodejsProject = [
  {
    image: IMAGES.inventoryApp,
    title: "Inventory App",
    desc: "An inventory management app for a toys store.",
    stack: ["Express", "MongoDB", "EJS"],
    code: "https://github.com/SonDo580/inventory-app",
  },
  {
    image: IMAGES.membershipSite,
    title: "Membership Site",
    desc: "An online membership club.",
    stack: ["Express", "MongoDB", "EJS", "PassportJS", "Bcrypt"],
    code: "https://github.com/SonDo580/members-only",
  },
  {
    image: IMAGES.mdnLibrary,
    title: "MDN Local Library",
    desc: "A library management app (guided project).",
    stack: ["Express", "MongoDB", "Pug", "Bootstrap"],
    code: "https://github.com/SonDo580/mdn-locallibrary",
  },
  {
    image: IMAGES.goalSetter,
    title: "Goal Setter",
    desc: "A MERN stack goal setting app (guided project).",
    stack: [
      "React",
      "React Router",
      "Redux",
      "Axios",
      "Express",
      "MongoDB",
      "Bcrypt",
      "JWT",
    ],
    code: "https://github.com/SonDo580/goal-setting",
  },
];

export { reactjsProjects, javascriptProjects, htmlProjects, nodejsProject };
